apiVersion: v1
kind: ServiceAccount
metadata:
  name: batteries-api
  namespace: battery-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batteries-api
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "namespaces", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: batteries-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: batteries-api
subjects:
- kind: ServiceAccount
  name: batteries-api
  namespace: battery-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batteries-api
  namespace: battery-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: batteries-api
  template:
    metadata:
      labels:
        app: batteries-api
    spec:
      serviceAccountName: batteries-api
      containers:
      - name: batteries-api
        image: battincacr26191.azurecr.io/batteries-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: batteries-api
  namespace: battery-core
spec:
  type: ClusterIP
  selector:
    app: batteries-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP